### PR TITLE
Replaced jbuild with dune files.

### PR DESCRIPTION
**Pull request by kc284**
Signed-off-by: Konstantina Chremmou <konstantina.chremmou@citrix.com>

### CODE REVIEW

**Comment by edwintorok** [comment]
The tests are failing on Travis: https://travis-ci.com/xapi-project/ezxenstore/builds/94029842
Previously I think we were not running the tests at all, not sure if you can somehow tell the tests that they are not inside a Xen environment and they should just use a simulator, or mocked functions.

**Comment by kc284** [comment]
For the time being the simplest is to disable the tests (it's a different piece of work).

**Comment by lindig** [comment]
What triggers the tests? If the tests were previously not run, I would agree to disable them for this PR.

**Comment by kc284** [comment]
I had added the run instruction to the opam file, but now I've removed it again.

**Review by lindig — APPROVED** [review]

**Pull request merged**
